// Generated by https://quicktype.io

export interface ForexPricesIndicatorResponse {
    prices: Price[];
}

export interface Price {
    Instrument: string;
    Time:       string;
    Bid:        number;
    Ask:        number;
    Indicator:  string;
}
