// Generated by https://quicktype.io

export interface ForexPricesResponse {
    prices: Price[];
}

export interface Price {
    Instrument: string;
    Time:       string;
    Bid:        number;
    Ask:        number;
}
