// Generated by https://quicktype.io

export interface ForexSessions {
    sessions: Session[];
}

export interface Session {
    Id:               string;
    idinfo:           string;
    SessionType:      string;
    ExperimentId:     string;
    StartDate:        string;
    EndDate:          string;
    LastUpdatedTime:  string;
    CurrentTime:      string;
    Strategy:         Strategy;
    SessionUser:      SessionUser;
    PercentComplete:  string;
    elapsedTime:      string;
    beginSessionTime: string;
    endSessionTime:   string;
    RealizedPL:       number;
    Balance:          number;//
}

export interface SessionUser {
    Id:                         null;
    idinfo:                     null;
    Status:                     null;
    Accounts:                   Accounts;
    RealizedPL:                 number;
    Balance:                    number;
    ClosedTrades:               number;
    PercentProfitableClosed:    number;
    OpenTrades:                 number;
    PercentProfitableOpen:      number;
}

export interface Accounts {
    Primary:   Account;
    Secondary: Account;
}

export interface Account {
    Id:             null;
    idinfo:         string;
    Cash:           number;
    Margin:         number;
    MarginRatio:    number;
    RealizedPl:     number;
    Trades:         any[];
    Orders:         Order[];
    ClosedTrades:   Trade[];
    BalanceHistory: BalanceHistory[];
    Idcount:        number;
}

export interface BalanceHistory {
    Date:   string;
    Amount: number;
}

export interface Trade {
    Id:         null;
    idinfo:     number;
    Pair:       Pair;
    Units:      number;
    OpenDate:   string;
    CloseDate:  null | string;
    Long:       boolean;
    OpenPrice:  number;
    ClosePrice: number;
    StopLoss:   number;
    TakeProfit: number;
    Init:       boolean;
    PL:         number;
}

export enum Pair {
    Audusd = "AUDUSD",
    Eurusd = "EURUSD",
    Gbpusd = "GBPUSD",
    Nzdusd = "NZDUSD",
    Usdcad = "USDCAD",
    Usdchf = "USDCHF",
    Usdjpy = "USDJPY",
}

export interface Order {
    ExpirationDate: null;
    Triggerprice:   number;
    Expired:        boolean;
    Above:          boolean;
    Trade:          Trade;
}

export interface Strategy {
    window:     number;
    ruleName:   string;
    position:   string;
    units:      number;
    stopLoss:   number;
    takeProfit: number;
}
