apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forex
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
    rules:
        - host: forex.{url_host}
          http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: forex
                    port: 
                      number: 80
    tls:
       - secretName: forex-tls
         hosts:
         - forex.{url_host}

---
apiVersion: v1
kind: Service
metadata:
  name: forex
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: forex-app
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: forex-app
spec:
  selector:
    matchLabels:
      app: forex-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: forex-app
    spec:
      containers:
      - name: forex-app
        image: emandere/forex-app-{platform}:{buildId}
        ports:
        - containerPort: 80
      nodeSelector:
        platform: {platform}
