apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forex
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
    rules:
        - http:
            paths:
            - path: /
              backend:
                serviceName: forex
                servicePort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: forex
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: forex-app
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: forex-app
spec:
  selector:
    matchLabels:
      app: forex-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: forex-app
    spec:
      containers:
      - name: forex-app
        image: emandere/forex-app-{platform}:{buildId}
        ports:
        - containerPort: 80